name: CI (release)

on:
  push:
    branches:
      - v1
  schedule:
    - cron: '0 6 * * 6'

jobs:
  try:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {sfml: latest, config: Release}
          - {sfml: nightly}
          - {sfml: '2.5.1', config: Debug}
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
          - os: ubuntu-latest
            config: {sfml: package}
          - os: macos-latest
            config: {sfml: package}

    name: sfml ${{ matrix.config.sfml }} ${{ matrix.config.config }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: npm install --only=prod
      - uses: oprypin/install-sfml@v1
        with: ${{ matrix.config }}
        id: install

      - run: |
          echo '${{ steps.install.outputs.sfml }}' : '${{ steps.install.outputs.path }}'
      - run: ls '${{ steps.install.outputs.path }}/include/SFML/System.hpp'

      - run: mv sfml-3-project/* sfml-project/
        if: matrix.config.sfml == 'nightly'
      - run: cmake . $(c="${{ matrix.config.config }}"; [[ $c ]] && echo -DCMAKE_BUILD_TYPE=$c)
        working-directory: sfml-project
      - run: cmake --build . $(c="${{ matrix.config.config }}"; [[ $c ]] && echo --config $c)
        working-directory: sfml-project

      - run: |
          Xvfb :99 -screen 0 1024x768x24 +extension GLX &
          echo DISPLAY=:99.0 >>$GITHUB_ENV
        if: runner.os == 'Linux'
      - run: ./$(c="${{ matrix.config.config }}"; >/dev/null ls "$c" && echo $c)/main
        working-directory: sfml-project
